export interface IMemberInfo {
  memberNameEN: string;
  memberNameJP: string;
  channelHandle: string;
  generation: string;
  status: 'active' | 'retired';
}

export const phaseConnectMembers: IMemberInfo[] = [
  {
    memberNameEN: 'Ashelia Rinkou',
    memberNameJP: 'アシェリア鈴香',
    channelHandle: '@RinkouAshelia',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Utatane Nasa',
    memberNameJP: '転寝ナサ',
    channelHandle: '@UtataneNasa',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Pipkin Pippa',
    memberNameJP: 'ピップキンピッパ',
    channelHandle: '@PipkinPippa',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Tenma Maemi',
    memberNameJP: '天満マエミ',
    channelHandle: '@TenmaMaemi',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Hakushika Iori',
    memberNameJP: '白鹿いおり',
    channelHandle: '@HakushikaIori',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Fujikura Uruka',
    memberNameJP: '藤倉ウルカ',
    channelHandle: '@FujikuraUruka',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Shisui Michiru',
    memberNameJP: '紫翠みちる',
    channelHandle: '@ShisuiMichiru',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEN: 'Kaneko Lumi',
    memberNameJP: '金子瑠美',
    channelHandle: '@KanekoLumi',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEN: 'Fuura Yuri',
    memberNameJP: 'ふうら百合',
    channelHandle: '@FuuraYuri',
    generation: 'Phase Invaders',
    status: 'retired',
  },
  {
    memberNameEN: 'Ember Amane',
    memberNameJP: '天音エンバー',
    channelHandle: '@EmberAmane',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEN: 'Dizzy Dokuro',
    memberNameJP: '髑髏ディズィー',
    channelHandle: '@dizzydokuro',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEN: 'Hoshiumi Jelly',
    memberNameJP: '星海ジェリー',
    channelHandle: '@JellyHoshiumi',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEN: 'Remilia Nephys',
    memberNameJP: 'レミリア・ネフィス',
    channelHandle: '@RemiliaNephys',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Chisaka Airi',
    memberNameJP: '千坂アイリ',
    channelHandle: '@ChisakaAiri',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Amanogawa Shiina',
    memberNameJP: '天ノ川しいな',
    channelHandle: '@AmanogawaShiina',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Himemiya Rie',
    memberNameJP: '姫宮りえ',
    channelHandle: '@HimemiyaRie',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Makina Erina',
    memberNameJP: 'エリナ・マキナ',
    channelHandle: '@ErinaMakina',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Komachi Panko',
    memberNameJP: '小町ぱんこ',
    channelHandle: '@komachipanko',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEN: 'Saya Sairroxs',
    memberNameJP: 'サヤ・サイロクサス',
    channelHandle: '@sayasairroxs',
    generation: 'Phase Euphoria',
    status: 'retired',
  },
  {
    memberNameEN: 'Runie Ruse',
    memberNameJP: 'ルニ・ルーズ',
    channelHandle: '@RunieRuse',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEN: 'Muu Muyu',
    memberNameJP: 'むうむゆ',
    channelHandle: '@MuuMuyu',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEN: 'Hikanari Hina',
    memberNameJP: '光鳴ひな',
    channelHandle: '@HikanariHina',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEN: 'Eimi Isami',
    memberNameJP: '勇エイミ',
    channelHandle: '@eimiisami',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEN: 'Kannagi Loki',
    memberNameJP: '巫ロキ',
    channelHandle: '@kannagiloki',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEN: 'Ayase Yuu',
    memberNameJP: '絢世・ユウ',
    channelHandle: '@ayaseyuu',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEN: 'Kaminari Clara',
    memberNameJP: '歌美鳴・クララ',
    channelHandle: '@kaminariclara',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEN: 'Kokoromo Memory',
    memberNameJP: '恋衣めもり',
    channelHandle: '@kokoromomemory_',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEN: 'Gram Pico',
    memberNameJP: '倉夢ぴこ',
    channelHandle: '@grampico',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
];
