export interface IMemberInfo {
  memberNameEn: string;
  memberNameJp: string;
  channelHandle: string;
  generation: string;
  status: 'active' | 'retired';
}

export const phaseConnectMembers: IMemberInfo[] = [
  {
    memberNameEn: 'Ashelia Rinkou',
    memberNameJp: 'アシェリア鈴香',
    channelHandle: '@RinkouAshelia',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Utatane Nasa',
    memberNameJp: '転寝ナサ',
    channelHandle: '@UtataneNasa',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Pipkin Pippa',
    memberNameJp: 'ピップキンピッパ',
    channelHandle: '@PipkinPippa',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Tenma Maemi',
    memberNameJp: '天満マエミ',
    channelHandle: '@TenmaMaemi',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Hakushika Iori',
    memberNameJp: '白鹿いおり',
    channelHandle: '@HakushikaIori',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Fujikura Uruka',
    memberNameJp: '藤倉ウルカ',
    channelHandle: '@FujikuraUruka',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Shisui Michiru',
    memberNameJp: '紫翠みちる',
    channelHandle: '@ShisuiMichiru',
    generation: 'Phase OriginS',
    status: 'active',
  },
  {
    memberNameEn: 'Kaneko Lumi',
    memberNameJp: '金子瑠美',
    channelHandle: '@KanekoLumi',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEn: 'Fuura Yuri',
    memberNameJp: 'ふうら百合',
    channelHandle: '@FuuraYuri',
    generation: 'Phase Invaders',
    status: 'retired',
  },
  {
    memberNameEn: 'Ember Amane',
    memberNameJp: '天音エンバー',
    channelHandle: '@EmberAmane',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEn: 'Dizzy Dokuro',
    memberNameJp: '髑髏ディズィー',
    channelHandle: '@dizzydokuro',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEn: 'Hoshiumi Jelly',
    memberNameJp: '星海ジェリー',
    channelHandle: '@JellyHoshiumi',
    generation: 'Phase Invaders',
    status: 'active',
  },
  {
    memberNameEn: 'Remilia Nephys',
    memberNameJp: 'レミリア・ネフィス',
    channelHandle: '@RemiliaNephys',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Chisaka Airi',
    memberNameJp: '千坂アイリ',
    channelHandle: '@ChisakaAiri',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Amanogawa Shiina',
    memberNameJp: '天ノ川しいな',
    channelHandle: '@AmanogawaShiina',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Himemiya Rie',
    memberNameJp: '姫宮りえ',
    channelHandle: '@HimemiyaRie',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Makina Erina',
    memberNameJp: 'エリナ・マキナ',
    channelHandle: '@ErinaMakina',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Komachi Panko',
    memberNameJp: '小町ぱんこ',
    channelHandle: '@komachipanko',
    generation: 'Phase ALiAS',
    status: 'active',
  },
  {
    memberNameEn: 'Saya Sairroxs',
    memberNameJp: 'サヤ・サイロクサス',
    channelHandle: '@sayasairroxs',
    generation: 'Phase Euphoria',
    status: 'retired',
  },
  {
    memberNameEn: 'Runie Ruse',
    memberNameJp: 'ルニ・ルーズ',
    channelHandle: '@RunieRuse',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEn: 'Muu Muyu',
    memberNameJp: 'むうむゆ',
    channelHandle: '@MuuMuyu',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEn: 'Hikanari Hina',
    memberNameJp: '光鳴ひな',
    channelHandle: '@HikanariHina',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEn: 'Eimi Isami',
    memberNameJp: '勇エイミ',
    channelHandle: '@eimiisami',
    generation: 'Phase Euphoria',
    status: 'active',
  },
  {
    memberNameEn: 'Kannagi Loki',
    memberNameJp: '巫ロキ',
    channelHandle: '@kannagiloki',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEn: 'Ayase Yuu',
    memberNameJp: '絢世・ユウ',
    channelHandle: '@ayaseyuu',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEn: 'Kaminari Clara',
    memberNameJp: '歌美鳴・クララ',
    channelHandle: '@kaminariclara',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEn: 'Kokoromo Memory',
    memberNameJp: '恋衣めもり',
    channelHandle: '@kokoromomemory_',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
  {
    memberNameEn: 'Gram Pico',
    memberNameJp: '倉夢ぴこ',
    channelHandle: '@grampico',
    generation: 'Phase KALEiDO',
    status: 'active',
  },
];
